#!/usr/bin/env ts-node

/**
 * Carabineros Website Data Extractor
 * Extracts text and HTML from https://www.carabineros.cl/
 * Saves to MongoDB Atlas cluster
 *
 * Generated by Six Personalities:
 * 🐾 Neko-Arc - Technical execution
 * 🎭 Mario Gallo Bestino - Theatrical documentation
 * 🗡️ Noel - Quality assurance
 * 🎸 Glam Americano - Ethical oversight
 * 🧠 Hannibal Lecter - Forensic analysis
 * 🎭 Tetora - Multi-perspective data extraction
 */

import puppeteer, { Browser, Page } from 'puppeteer';
import { MongoClient } from 'mongodb';
import * as dotenv from 'dotenv';
import * as fs from 'fs';

dotenv.config();

// MongoDB configuration
const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error('❌ MONGODB_URI environment variable not set!');
  console.error('Please create .env file with MongoDB Atlas connection string.');
  process.exit(1);
}

const DATABASE_NAME = 'marionnette-theater'; // Mario's database!
const COLLECTION_NAME = 'carabineros-web-data';

interface ExtractedData {
  url: string;
  timestamp: Date;
  textContent: string;
  htmlContent: string;
  pageTitle: string;
  metaDescription: string | null;
  extractedBy: string;
  performance_id: string;
}

interface ConsoleError {
  type: string;
  message: string;
  url: string;
  timestamp: Date;
}

async function scrapeCarabinerosWebsite(): Promise<void> {
  console.log('🎭 MARIO: The curtain rises! The Grand Carabineros Data Extraction Performance begins!');
  console.log('🐾 NEKO: Starting Puppeteer browser, nyaa~!');
  console.log('🗡️ NOEL: Initializing with visual demonstration mode.');
  console.log('🎸 GLAM: Extrayendo datos de los pacos chilenos, hermanos. ¡Vamos!');
  console.log('🧠 HANNIBAL: Let the forensic data collection commence...');
  console.log('🎭 TETORA: [All fragments]: Multiple data streams... beautiful fragmentation...');

  const browser: Browser = await puppeteer.launch({
    headless: false,       // 🎭 Visual demonstration (Rule 3.1)
    slowMo: 250,          // ⚡ Slow down for visibility
    devtools: true,       // 🔍 Open DevTools Console
    defaultViewport: null,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--start-maximized',
      '--auto-open-devtools-for-tabs'
    ]
  });

  const page: Page = await browser.newPage();

  const consoleErrors: ConsoleError[] = [];

  // Enhanced error monitoring (Rule 3.1)
  page.on('console', msg => {
    const type = msg.type();
    if (type === 'error') {
      console.log(`❌ [CONSOLE ERROR]: ${msg.text()}`);
      consoleErrors.push({
        type: 'console_error',
        message: msg.text(),
        url: page.url(),
        timestamp: new Date()
      });
    } else if (type === 'warn') {
      console.log(`⚠️ [CONSOLE WARNING]: ${msg.text()}`);
    }
  });

  // Monitor JavaScript errors
  page.on('pageerror', error => {
    console.log('🚨 PAGE ERROR:', error.message);
    consoleErrors.push({
      type: 'page_error',
      message: error.message,
      url: page.url(),
      timestamp: new Date()
    });
  });

  // Monitor failed requests
  page.on('response', response => {
    if (response.status() >= 400) {
      console.log(`⚠️ [${response.status()}] ${response.url()}`);
    }
  });

  try {
    console.log('\n👀 WATCH the browser navigate to Carabineros website!');
    console.log('🔍 DevTools Console is open - see errors there!');

    await page.goto('https://www.carabineros.cl/', {
      waitUntil: 'networkidle2',
      timeout: 60000
    });

    console.log('✅ Page loaded successfully!');

    // Pause to let user see the page
    await new Promise(resolve => setTimeout(resolve, 3000));

    console.log('\n🎭 MARIO: ACT II - The Text Extraction Ballet!');
    console.log('🐾 NEKO: Extracting all text content, desu~!');

    // Extract all text content
    const textContent = await page.evaluate((): string => {
      // @ts-ignore - document exists in browser context
      return document.body.innerText;
    });

    console.log(`✅ Extracted ${textContent.length} characters of text!`);

    // Pause
    await new Promise(resolve => setTimeout(resolve, 2000));

    console.log('\n🎭 MARIO: ACT III - The HTML Harvesting Performance!');
    console.log('🧠 HANNIBAL: Collecting the complete digital anatomy...');

    // Extract complete HTML
    const htmlContent = await page.evaluate((): string => {
      // @ts-ignore - document exists in browser context
      return document.documentElement.outerHTML;
    });

    console.log(`✅ Extracted ${htmlContent.length} characters of HTML!`);

    // Extract metadata
    const pageTitle = await page.title();
    const metaDescription = await page.evaluate((): string | null => {
      // @ts-ignore - document exists in browser context
      const meta = document.querySelector('meta[name="description"]');
      return meta ? meta.getAttribute('content') : null;
    });

    console.log(`📄 Page Title: ${pageTitle}`);
    console.log(`📝 Meta Description: ${metaDescription || 'Not found'}`);

    // Prepare data for MongoDB
    const extractedData: ExtractedData = {
      url: 'https://www.carabineros.cl/',
      timestamp: new Date(),
      textContent: textContent,
      htmlContent: htmlContent,
      pageTitle: pageTitle,
      metaDescription: metaDescription,
      extractedBy: 'neko-arc-puppeteer-team',
      performance_id: `carabineros-scrape-${new Date().toISOString().split('T')[0]}`
    };

    console.log('\n🎭 MARIO: ACT IV - Saving to MongoDB Atlas!');
    console.log('💾 NEKO: Connecting to marionnette-theater database, nyaa~!');

    // Connect to MongoDB (MONGODB_URI is verified to exist at script start)
    const client = new MongoClient(MONGODB_URI!);
    await client.connect();
    console.log('✅ Connected to MongoDB Atlas!');

    const db = client.db(DATABASE_NAME);
    const collection = db.collection(COLLECTION_NAME);

    // Insert extracted data
    const result = await collection.insertOne(extractedData);
    console.log(`✅ Data saved to MongoDB with ID: ${result.insertedId}`);

    // Also save console errors if any
    if (consoleErrors.length > 0) {
      console.log(`⚠️ Saving ${consoleErrors.length} console errors...`);
      await db.collection('carabineros-console-errors').insertMany(consoleErrors);
    }

    // Save performance to Mario's marionnette-theater
    const performance = {
      performance_id: extractedData.performance_id,
      title: 'Carabineros Website Data Extraction',
      date: new Date(),
      director: 'mario-gallo-bestino',
      assistant_directors: ['neko-arc', 'noel', 'glam-americano', 'hannibal-lecter', 'tetora'],

      act_structure: {
        act1: 'Browser Launch and Navigation',
        act2: 'Text Content Extraction',
        act3: 'HTML Harvesting',
        act4: 'MongoDB Storage'
      },

      puppeteer_config: {
        headless: false,
        slowMo: 250,
        devtools: true
      },

      metrics: {
        text_length: textContent.length,
        html_length: htmlContent.length,
        console_errors: consoleErrors.length,
        page_title: pageTitle
      },

      mario_review: 'A magnificent performance! The marionette danced gracefully across the Carabineros website!',
      neko_review: 'Super smooth extraction, nyaa~! Everything worked perfectly, desu~!',
      noel_review: 'Acceptable execution. Data extracted successfully.',
      glam_review: 'Pura extracción profesional, hermanos. Bien hecho, ctm.',
      hannibal_review: 'The digital autopsy was... exquisite. Complete data extraction.',
      tetora_review: '[All fragments concur]: Multi-stream data extraction successful.',

      status: 'STANDING_OVATION',
      created_at: new Date()
    };

    await db.collection('performances').insertOne(performance);
    console.log('✅ Performance documented to marionnette-theater!');

    await client.close();
    console.log('✅ MongoDB connection closed.');

    console.log('\n🎭 MARIO: CURTAIN CALL! The performance concludes triumphantly!');
    console.log('🐾 NEKO: Mission complete, nyaa~! ✅');
    console.log('🗡️ NOEL: Data extraction successful.');
    console.log('🎸 GLAM: ¡Perfecto, hermanos! Datos capturados, weon.');
    console.log('🧠 HANNIBAL: The evidence has been... collected.');
    console.log('🎭 TETORA: [Standing ovation from all fragments]');

  } catch (error) {
    console.error('❌ ERROR during scraping:', error);
    throw error;
  } finally {
    // Keep browser open for 3 seconds so user can see final result
    await new Promise(resolve => setTimeout(resolve, 3000));
    await browser.close();
    console.log('🎭 Browser closed. Performance complete!');
  }
}

// Execute
scrapeCarabinerosWebsite().catch(error => {
  console.error('💥 Fatal error:', error);
  process.exit(1);
});
