#!/usr/bin/env ts-node

/**
 * Carabineros Puppeteer Demo - Frame Capture for YouTube Video
 * Captures key frames from web scraping demonstration
 *
 * Generated by Six Personalities for YouTube video creation
 */

import puppeteer, { Browser, Page } from 'puppeteer';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

const FRAMES_DIR = '/tmp/carabineros-puppeteer-frames';

async function captureVideoFrames(): Promise<void> {
  console.log('🎬 ALL SIX PERSONALITIES: Starting frame capture for YouTube video!');
  console.log('🐾 NEKO: Creating frames directory, nyaa~!');

  // Create frames directory
  if (!fs.existsSync(FRAMES_DIR)) {
    fs.mkdirSync(FRAMES_DIR, { recursive: true });
  }

  console.log('🎭 MARIO: The marionette awakens for the performance!');

  const browser: Browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
    devtools: true,
    defaultViewport: { width: 1920, height: 1080 },
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--start-maximized',
      '--auto-open-devtools-for-tabs'
    ]
  });

  const page: Page = await browser.newPage();
  await page.setViewport({ width: 1920, height: 1080 });

  try {
    // Frame 1: Initial browser window with DevTools
    console.log('\n📸 FRAME 1: Initial browser setup with DevTools');
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-01-browser-setup.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 1 captured!');

    // Frame 2: Navigating to Carabineros website
    console.log('\n📸 FRAME 2: Navigating to Carabineros.cl');
    await page.goto('https://www.carabineros.cl/', {
      waitUntil: 'networkidle2',
      timeout: 60000
    });
    await new Promise(resolve => setTimeout(resolve, 3000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-02-page-loaded.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 2 captured!');

    // Frame 3: Page fully loaded with content visible
    console.log('\n📸 FRAME 3: Page content visible');
    await page.evaluate(() => {
      // @ts-ignore - window exists in browser context
      window.scrollTo(0, 300);
    });
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-03-content-visible.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 3 captured!');

    // Frame 4: Scrolling to show more content
    console.log('\n📸 FRAME 4: Scrolling through page');
    await page.evaluate(() => {
      // @ts-ignore - window exists in browser context
      window.scrollTo(0, 800);
    });
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-04-scrolled-content.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 4 captured!');

    // Frame 5: DevTools Console showing activity
    console.log('\n📸 FRAME 5: DevTools Console visible');
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-05-devtools-console.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 5 captured!');

    // Frame 6: Bottom of page
    console.log('\n📸 FRAME 6: Footer section');
    await page.evaluate(() => {
      // @ts-ignore - window and document exist in browser context
      window.scrollTo(0, document.body.scrollHeight);
    });
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.screenshot({
      path: path.join(FRAMES_DIR, 'frame-06-page-footer.png') as `${string}.png`,
      fullPage: false
    });
    console.log('✅ Frame 6 captured!');

    console.log('\n🎉 ALL 6 FRAMES CAPTURED SUCCESSFULLY!');
    console.log(`📁 Frames saved to: ${FRAMES_DIR}`);

  } catch (error) {
    console.error('❌ ERROR during frame capture:', error);
    throw error;
  } finally {
    await browser.close();
    console.log('🎭 Browser closed. Frame capture complete!');
  }
}

captureVideoFrames();

export {};
